DO $$ BEGIN
 CREATE TYPE "public"."contactMean" AS ENUM('mail', 'phone', 'in person', 'unknown');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."itemType" AS ENUM('postcard', 'stationery', 'game', 'book', 'magazine', 'unknown', 'dvd', 'deposit');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."orderStatus" AS ENUM('new', 'received', 'unavailable', 'canceled', 'done', 'other');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."paymentType" AS ENUM('cash', 'card', 'check', 'check-lire', 'transfer');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."role" AS ENUM('admin', 'guest');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."tva" AS ENUM('20', '5.5', '2.1', '0');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "asideCart" (
	"id" integer PRIMARY KEY NOT NULL,
	"itemId" integer,
	"type" "itemType" NOT NULL,
	"title" varchar NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"tva" "tva" NOT NULL,
	"quantity" integer NOT NULL,
	"userId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"itemId" integer,
	"type" "itemType" NOT NULL,
	"title" varchar NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"tva" "tva" NOT NULL,
	"quantity" integer NOT NULL,
	"userId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "customers" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"_id" varchar NOT NULL,
	"fullname" varchar NOT NULL,
	"nmFullname" varchar NOT NULL,
	"contact" varchar NOT NULL,
	"phone" varchar,
	"email" varchar,
	"comment" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "items" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"_id" varchar NOT NULL,
	"type" "itemType" NOT NULL,
	"isbn" varchar(13) NOT NULL,
	"author" varchar NOT NULL,
	"title" varchar NOT NULL,
	"publisher" varchar NOT NULL,
	"distributor" varchar NOT NULL,
	"keywords" varchar,
	"datebought" char(10) NOT NULL,
	"comments" varchar,
	"price" numeric(12, 2) NOT NULL,
	"amount" integer NOT NULL,
	"tva" "tva" NOT NULL,
	"starred" boolean NOT NULL,
	"nmAuthor" varchar NOT NULL,
	"nmTitle" varchar NOT NULL,
	"nmPublisher" varchar NOT NULL,
	"nmDistributor" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "orders" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created" timestamp with time zone DEFAULT now() NOT NULL,
	"customerId" integer,
	"customerObjectId" varchar,
	"itemId" integer,
	"itemObjectId" varchar,
	"itemTitle" varchar NOT NULL,
	"ordered" "orderStatus" NOT NULL,
	"customerNotified" boolean NOT NULL,
	"paid" boolean NOT NULL,
	"comment" varchar NOT NULL,
	"nb" integer NOT NULL,
	"contact" "contactMean" DEFAULT 'unknown' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "purchases" (
	"date" varchar NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"customerId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sales" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sales_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"itemType" "itemType" NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"quantity" integer NOT NULL,
	"title" varchar,
	"created" timestamp with time zone DEFAULT now() NOT NULL,
	"tva" "tva",
	"linkedToCustomer" boolean NOT NULL,
	"itemObjectId" varchar,
	"itemId" integer,
	"cartId" integer,
	"deleted" boolean NOT NULL,
	"paymentType" "paymentType"
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "selectedCustomer" (
	"asideCart" boolean NOT NULL,
	"userId" integer NOT NULL,
	"customerId" integer,
	CONSTRAINT "selectedCustomer_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"hash" char(60) NOT NULL,
	"role" "role" NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "asideCart" ADD CONSTRAINT "asideCart_itemId_items_id_fk" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "asideCart" ADD CONSTRAINT "asideCart_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cart" ADD CONSTRAINT "cart_itemId_items_id_fk" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cart" ADD CONSTRAINT "cart_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "orders" ADD CONSTRAINT "orders_customerId_customers_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "orders" ADD CONSTRAINT "orders_itemId_items_id_fk" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "purchases" ADD CONSTRAINT "purchases_customerId_customers_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sales" ADD CONSTRAINT "sales_itemId_items_id_fk" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "selectedCustomer" ADD CONSTRAINT "selectedCustomer_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "selectedCustomer" ADD CONSTRAINT "selectedCustomer_customerId_customers_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
