UPDATE "cart" AS c
SET "quantity" = d.total
FROM (
  SELECT "itemId", "userId", MIN("id") AS keep_id, SUM("quantity") AS total
  FROM "cart"
  WHERE "itemId" IS NOT NULL
  GROUP BY "itemId", "userId"
  HAVING COUNT(*) > 1
) AS d
WHERE c."id" = d.keep_id;--> statement-breakpoint
DELETE FROM "cart" AS a
USING "cart" AS b
WHERE a."id" > b."id"
  AND a."itemId" = b."itemId"
  AND a."userId" = b."userId"
  AND a."itemId" IS NOT NULL;--> statement-breakpoint
UPDATE "asideCart" AS c
SET "quantity" = d.total
FROM (
  SELECT "itemId", "userId", MIN("id") AS keep_id, SUM("quantity") AS total
  FROM "asideCart"
  WHERE "itemId" IS NOT NULL
  GROUP BY "itemId", "userId"
  HAVING COUNT(*) > 1
) AS d
WHERE c."id" = d.keep_id;--> statement-breakpoint
DELETE FROM "asideCart" AS a
USING "asideCart" AS b
WHERE a."id" > b."id"
  AND a."itemId" = b."itemId"
  AND a."userId" = b."userId"
  AND a."itemId" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "asideCart" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "asideCart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval(
  pg_get_serial_sequence('"asideCart"', 'id'),
  COALESCE((SELECT MAX("id") FROM "asideCart"), 1),
  (SELECT COUNT(*) > 0 FROM "asideCart")
);--> statement-breakpoint
CREATE INDEX "asideCart_userId_idx" ON "asideCart" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "asideCart_item_user_unique" ON "asideCart" USING btree ("itemId","userId") WHERE "asideCart"."itemId" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "cart_userId_idx" ON "cart" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "cart_item_user_unique" ON "cart" USING btree ("itemId","userId") WHERE "cart"."itemId" IS NOT NULL;
