packages:
  - apps/*
  - packages/*
  - tests

allowBuilds:
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

minimumReleaseAgeExclude:
  - eslint-plugin-vue@10.11.1

packageExtensions:
  drizzle-kit:
    dependencies:
      postgres: "3.4.9"
