ALTER TABLE "orders" ALTER COLUMN "customerId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "id" integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "purchases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "selectedCustomer" ADD COLUMN "id" integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "selectedCustomer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
CREATE INDEX "items_nmAuthor_idx" ON "items" USING btree ("nmAuthor");--> statement-breakpoint
CREATE INDEX "items_nmTitle_idx" ON "items" USING btree ("nmTitle");--> statement-breakpoint
CREATE INDEX "items_nmPublisher_idx" ON "items" USING btree ("nmPublisher");--> statement-breakpoint
CREATE INDEX "items_nmDistributor_idx" ON "items" USING btree ("nmDistributor");--> statement-breakpoint
UPDATE "items" SET "isbn" = '' WHERE "isbn" ~ '^\s*$';--> statement-breakpoint
CREATE UNIQUE INDEX "items_isbn_unique" ON "items" USING btree ("isbn") WHERE "items"."isbn" != '';--> statement-breakpoint
CREATE INDEX "orders_customerId_idx" ON "orders" USING btree ("customerId");--> statement-breakpoint
CREATE INDEX "orders_ordered_idx" ON "orders" USING btree ("ordered");--> statement-breakpoint
CREATE INDEX "purchases_customerId_idx" ON "purchases" USING btree ("customerId");--> statement-breakpoint
CREATE INDEX "sales_itemId_idx" ON "sales" USING btree ("itemId");--> statement-breakpoint
CREATE INDEX "sales_deleted_idx" ON "sales" USING btree ("deleted");--> statement-breakpoint
CREATE INDEX "sales_created_idx" ON "sales" USING btree ("created");